apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi

---

apiVersion: v1
kind: Service
metadata:
  labels:
    metrics: grafana
  name: grafana-svc
spec:
  ports:
    - port: 3000
      protocol: TCP
      targetPort: 3000
  selector:
    metrics: grafana
  sessionAffinity: None
  type: ClusterIP

---

apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  labels:
    metrics: grafana
  name: grafana
spec:
  replicas: 1
  selector:
    metrics: grafana
  template:
    metadata:
      creationTimestamp: null
      labels:
        metrics: grafana
    spec:
      containers:
        - env:
            - name: INFLUXDB_HOST
              value: influxdb-svc
          image: grafana/grafana-oss:8.5.9
          imagePullPolicy: Always
          name: grafana
          ports:
            - containerPort: 3000
              protocol: TCP
          volumeMounts:
            - mountPath: /var/lib/grafana
              name: grafana-data
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      volumes:
        - name: grafana-data
          persistentVolumeClaim:
            claimName: grafana-data
  test: false
  triggers:
    - type: ConfigChange

---

apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    metrics: grafana
  name: grafana-route
spec:
  to:
    kind: Service
    name: grafana-svc
