apiVersion: v1
kind: Service
metadata:
  name: mqtt-broker
spec:
  ports:
    - name: port-1
      port: 1883
      protocol: TCP
      targetPort: 1883
    - name: port-2
      port: 9001
      protocol: TCP
      targetPort: 9001
  selector:
    app: mqtt-broker
