apiVersion: apps/v1
kind: Deployment
metadata:
  name: mqtt-kafka-bridge
spec:
  selector:
    matchLabels:
      app: mqtt-kafka-bridge
  replicas: 1
  template:
    metadata:
      labels:
        app: mqtt-kafka-bridge
    spec:
      containers:
        - name: mqtt-kafka-bridge
          image: >-
            docker.io/frizzorossi/quarkus-edge-mqtt-demo
          ports:
            - containerPort: 8080
          env:
            - name: KAFKA_BOOTSTRAP
              value: ae60f20d9caed492987c84b17094761b-537900584.us-east-2.elb.amazonaws.com:9094
            - name: DEVICE_NAME
              value: my_device

